### ISSUE TITLE
For LONGBLOB columns, SQLColAttribute returns different values for SQL_COLUMN_LENGTH and SQL_DESC_LENGTH

### ISSUE THREAD

**Issue by vkr-ayx** [memsql/singlestore-odbc-connector#12]
I'm using SingleStore driver 1.1.5. When calling SQLColAttribute function on LONGBLOB column, different values are returned for these FieldIdentifiers:

`SQL_COLUMN_LENGTH`: **2147483647**
`SQL_DESC_OCTET_LENGTH`: **2147483647**
`SQL_DESC_LENGTH`:  **4294967295**

I would expect the same value to be returned for all of these.

For MEDIUMBLOB type, all the lengths returned are the same, as expected (**16777215**).

DDL used for creating the table under test:
`CREATE TABLE platform_tests.read_datatypes(TINYBLOB1 TINYBLOB, BLOB1 BLOB, MEDIUMBLOB1 MEDIUMBLOB, LONGBLOB1 LONGBLOB);`

**Comment by pmishchenko-ua** [comment]
According to SingleStore docs, https://docs.singlestore.com/cloud/reference/sql-reference/data-types/blob-types/ 4294967295 is allowed for DDL, but actually data larger than 1 GB can't be stored, so I'm going to update the driver so that these values are changed to 1073741823.
