### ISSUE TITLE
SQLPrimaryKeys crash information_schema.schemata

### ISSUE THREAD

**Issue by faridzidan** [memsql/singlestore-odbc-connector#8]
Windows 10 x64
SingleStore 07.08.0017
MemSQL source distribution (compatible; MySQL Enterprise & MySQL Commercial)
ssodbca.dll 01.01.0000

Driver crashes on trying to execute SQLPrimaryKeys for information_schema.schemata table.
This works fine with MySQL ODBC driver and SingleStore 1.04 ODBC driver, but not with latest SingleStore ODBC Driver ANSI 1.1.0.

Exception thrown: read access violation.
**table_row** was nullptr.

The crash does not happen if executing SQLPrimaryKeys on a user table.

![SQLPrimaryKeys crash 2022-10-17 121458](https://user-images.githubusercontent.com/11477995/196231501-3c6c63a2-eb1d-46df-a5c9-ebd51a82b2b5.jpg)

**Comment by pmishchenko-ua** [comment]
Fixed in https://github.com/memsql/singlestore-odbc-connector/releases/tag/v1.1.2
